/* Auto-generated by genmsg_cpp for file /tmp/buildd/ros-groovy-hector-quadrotor-0.2.3/debian/ros-groovy-hector-quadrotor/opt/ros/groovy/stacks/hector_quadrotor/hector_uav_msgs/msg/Supply.msg */
#ifndef HECTOR_UAV_MSGS_MESSAGE_SUPPLY_H
#define HECTOR_UAV_MSGS_MESSAGE_SUPPLY_H
#include <string>
#include <vector>
#include <map>
#include <ostream>
#include "ros/serialization.h"
#include "ros/builtin_message_traits.h"
#include "ros/message_operations.h"
#include "ros/time.h"

#include "ros/macros.h"

#include "ros/assert.h"

#include "std_msgs/Header.h"

namespace hector_uav_msgs
{
template <class ContainerAllocator>
struct Supply_ {
  typedef Supply_<ContainerAllocator> Type;

  Supply_()
  : header()
  , voltage()
  , current()
  {
  }

  Supply_(const ContainerAllocator& _alloc)
  : header(_alloc)
  , voltage(_alloc)
  , current(_alloc)
  {
  }

  typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
   ::std_msgs::Header_<ContainerAllocator>  header;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _voltage_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  voltage;

  typedef std::vector<float, typename ContainerAllocator::template rebind<float>::other >  _current_type;
  std::vector<float, typename ContainerAllocator::template rebind<float>::other >  current;


  typedef boost::shared_ptr< ::hector_uav_msgs::Supply_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::hector_uav_msgs::Supply_<ContainerAllocator>  const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;
}; // struct Supply
typedef  ::hector_uav_msgs::Supply_<std::allocator<void> > Supply;

typedef boost::shared_ptr< ::hector_uav_msgs::Supply> SupplyPtr;
typedef boost::shared_ptr< ::hector_uav_msgs::Supply const> SupplyConstPtr;


template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const  ::hector_uav_msgs::Supply_<ContainerAllocator> & v)
{
  ros::message_operations::Printer< ::hector_uav_msgs::Supply_<ContainerAllocator> >::stream(s, "", v);
  return s;}

} // namespace hector_uav_msgs

namespace ros
{
namespace message_traits
{
template<class ContainerAllocator> struct IsMessage< ::hector_uav_msgs::Supply_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct IsMessage< ::hector_uav_msgs::Supply_<ContainerAllocator>  const> : public TrueType {};
template<class ContainerAllocator>
struct MD5Sum< ::hector_uav_msgs::Supply_<ContainerAllocator> > {
  static const char* value() 
  {
    return "26f5225a2b836fba706a87e45759fdfc";
  }

  static const char* value(const  ::hector_uav_msgs::Supply_<ContainerAllocator> &) { return value(); } 
  static const uint64_t static_value1 = 0x26f5225a2b836fbaULL;
  static const uint64_t static_value2 = 0x706a87e45759fdfcULL;
};

template<class ContainerAllocator>
struct DataType< ::hector_uav_msgs::Supply_<ContainerAllocator> > {
  static const char* value() 
  {
    return "hector_uav_msgs/Supply";
  }

  static const char* value(const  ::hector_uav_msgs::Supply_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator>
struct Definition< ::hector_uav_msgs::Supply_<ContainerAllocator> > {
  static const char* value() 
  {
    return "Header header\n\
float32[] voltage\n\
float32[] current\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.secs: seconds (stamp_secs) since epoch\n\
# * stamp.nsecs: nanoseconds since stamp_secs\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
";
  }

  static const char* value(const  ::hector_uav_msgs::Supply_<ContainerAllocator> &) { return value(); } 
};

template<class ContainerAllocator> struct HasHeader< ::hector_uav_msgs::Supply_<ContainerAllocator> > : public TrueType {};
template<class ContainerAllocator> struct HasHeader< const ::hector_uav_msgs::Supply_<ContainerAllocator> > : public TrueType {};
} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

template<class ContainerAllocator> struct Serializer< ::hector_uav_msgs::Supply_<ContainerAllocator> >
{
  template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
  {
    stream.next(m.header);
    stream.next(m.voltage);
    stream.next(m.current);
  }

  ROS_DECLARE_ALLINONE_SERIALIZER;
}; // struct Supply_
} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::hector_uav_msgs::Supply_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const  ::hector_uav_msgs::Supply_<ContainerAllocator> & v) 
  {
    s << indent << "header: ";
s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "voltage[]" << std::endl;
    for (size_t i = 0; i < v.voltage.size(); ++i)
    {
      s << indent << "  voltage[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.voltage[i]);
    }
    s << indent << "current[]" << std::endl;
    for (size_t i = 0; i < v.current.size(); ++i)
    {
      s << indent << "  current[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.current[i]);
    }
  }
};


} // namespace message_operations
} // namespace ros

#endif // HECTOR_UAV_MSGS_MESSAGE_SUPPLY_H

