set(_CATKIN_CURRENT_PACKAGE "moveit_simple_controller_manager")
set(moveit_simple_controller_manager_MAINTAINER "Michael Ferguson <fergs@unboundedrobotics.com>")
set(moveit_simple_controller_manager_DEPRECATED "")
set(moveit_simple_controller_manager_VERSION "0.5.2")
set(moveit_simple_controller_manager_BUILD_DEPENDS "moveit_core" "roscpp" "pluginlib" "control_msgs" "actionlib")
set(moveit_simple_controller_manager_RUN_DEPENDS "moveit_core" "roscpp" "pluginlib" "control_msgs" "actionlib")
set(moveit_simple_controller_manager_BUILDTOOL_DEPENDS "catkin")